name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          python3-dev \
          autoconf \
          libtool \
          pkg-config \
          libffi-dev \
          libssl-dev

    - name: Install Buildozer
      run: pip install buildozer

    - name: Build APK
      run: |
        buildozer -v android release
        cp bin/*.apk .

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: collision-demo-apk
        path: ./*.apk
